# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e70d52a4184144806a807162f389eb7be6d3db621f7f224e7b74c8e8306878f814d25d6f199a55c6d1a477dcc26a4a29ba42b2531d9fef1726c2bbebc310a95

test:
  secret_key_base: de6d11fd632bc606b3503de0e47220955d5f9b3626e67108fb70a4351c35c28c91ce644bee646ed0a167e4b724569fd59fc92e1dc9ecfc35a0a92ce5b34a4710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
